apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: globalserver-hpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: global-server
  targetCPUUtilizationPercentage: 50