apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: koreaserver-hpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: korea-server
  targetCPUUtilizationPercentage: 50